name: jijian
description: 秒薪计件 - 免费本地版计件工资App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.3
  share_plus: ^10.1.2
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
